description: Prepares the repo for a typical CI job

name: prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: "20"
    - run: pnpm install
      shell: bash
  using: composite
